//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyCinemas.DBtEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingNumber { get; set; }
        public int SessionID { get; set; }
        public byte Quantity { get; set; }
        public string Special { get; set; }
        public decimal Discount { get; set; }
        public decimal FinalPrice { get; set; }
        public decimal OriginalPrice { get; set; }
    }
}
